#!/bin/sh
set -ex

RACK_ENV="test"
DATABASE_URL="mysql2://root@localhost/janky_test"
export RACK_ENV DATABASE_URL
export RBENV_VERSION="2.0.0-github"

test -n "$RBENV_VERSION" && {
  export PATH="/usr/share/rbenv/shims:$PATH"
  DBNAME=`echo "${RBENV_VERSION}" | sed  -e 's/[\.|\-]/_/g'`
  export DATABASE_URL="${DATABASE_URL}_${DBNAME}"
}

hostname
ruby -v
env
bundle install --binstubs --path vendor/gems
mysql -u root -e "CREATE DATABASE IF NOT EXISTS janky_test_${DBNAME}"
bin/rake db:migrate --trace
bundle exec script/test
